---

- name: create CA key
  community.crypto.openssl_privatekey:
    path: "{{cert_dir}}/{{cert_domain_ca}}.key"
    force: "{{cert_overwrite}}"
  register: ca_key

- name: create the CA CSR
  community.crypto.openssl_csr:
    path: "{{cert_dir}}/{{cert_domain_ca}}.csr"
    privatekey_path: "{{ ca_key.filename }}"
    # constraints and usage required by CA
    basic_constraints_critical: true
    basic_constraints:
      - CA:TRUE
      - pathlen:0
    key_usage:
      - digitalSignature
      - cRLSign
      - keyCertSign
    common_name: "{{cert_domain_ca}}"
    force: "{{cert_overwrite}}"
  register: ca_csr

- name: sign the CA CSR
  openssl_certificate:
    path: "{{cert_dir}}/{{cert_domain_ca}}.crt"
    csr_path: "{{ ca_csr.filename }}"
    privatekey_path: "{{ ca_key.filename }}"
    provider: selfsigned
    force: "{{cert_overwrite}}"
  register: ca_crt

