# dependency on: ansible-galaxy collection install community.crypto
# needs PyOpenSSL or cryptogrphy
---

- name: create CA cert, but only if CA defined
  # 'include_' does static removal so tasks inside not even considered
  # 'import_' does dynamic removal so tasks are brought in, but then skipped
  #import_tasks: ca.yml
  include_tasks: ca.yml
  when: cert_domain_ca is defined

- name: create certificate
  import_tasks: cert.yml
  when: 
